title: Advait Patole # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Pursuing Masters in Robotics at University of Maryland College Park
  <br><br>
  Interested in Autonomous Systems.
  <br><br>
  <a href="https://www.linkedin.com/in/advait-patole-06a09b113/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-cayman
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
